<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4Gwz2Mk' shared service.

return $this->privates['.service_locator.4Gwz2Mk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'buildingRepository' => array('privates', 'App\\Repository\\BuildingRepository', 'getBuildingRepositoryService.php', true),
    'slideRepository' => array('privates', 'App\\Repository\\SlideRepository', 'getSlideRepositoryService.php', true),
));
