<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'admin.slide' autowired service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\AccessRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\FieldDescriptionRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\LifecycleHookProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\MenuBuilderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\ParentAdminInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\UrlGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\AdminInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-acl\\Model\\DomainObjectInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\AdminTreeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Admin\\AbstractAdmin.php';
include_once $this->targetDirs[3].'\\src\\Admin\\SlideAdmin.php';
include_once $this->targetDirs[3].'\\src\\Admin\\BuildingAdmin.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Security\\Handler\\SecurityHandlerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Security\\Handler\\NoopSecurityHandler.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Translator\\LabelTranslatorStrategyInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Translator\\NativeLabelTranslatorStrategy.php';

$this->factories['admin.slide'] = function () {
    $instance = new \App\Admin\SlideAdmin('admin.slide', 'App\\Entity\\Slide', 'App\\Controller\\SlideAdminController');

    $a = new \App\Admin\BuildingAdmin('admin.building', 'App\\Entity\\Building', 'Sonata\\AdminBundle\\Controller\\CRUDController');

    $b = ($this->services['sonata.admin.manager.orm'] ?? $this->load('getSonata_Admin_Manager_OrmService.php'));
    $c = ($this->privates['sonata.admin.builder.orm_form'] ?? $this->load('getSonata_Admin_Builder_OrmFormService.php'));
    $d = ($this->privates['sonata.admin.builder.orm_show'] ?? $this->load('getSonata_Admin_Builder_OrmShowService.php'));
    $e = ($this->privates['sonata.admin.builder.orm_list'] ?? $this->load('getSonata_Admin_Builder_OrmListService.php'));
    $f = ($this->privates['sonata.admin.builder.orm_datagrid'] ?? $this->load('getSonata_Admin_Builder_OrmDatagridService.php'));
    $g = ($this->services['translator'] ?? $this->getTranslatorService());
    $h = ($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService());
    $i = ($this->services['sonata.admin.route.default_generator'] ?? $this->load('getSonata_Admin_Route_DefaultGeneratorService.php'));
    $j = ($this->services['validator'] ?? $this->getValidatorService());
    $k = ($this->privates['sonata.admin.security.handler.noop'] ?? ($this->privates['sonata.admin.security.handler.noop'] = new \Sonata\AdminBundle\Security\Handler\NoopSecurityHandler()));
    $l = ($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php'));
    $m = ($this->services['sonata.admin.route.path_info'] ?? $this->load('getSonata_Admin_Route_PathInfoService.php'));
    $n = ($this->services['sonata.admin.label.strategy.native'] ?? ($this->services['sonata.admin.label.strategy.native'] = new \Sonata\AdminBundle\Translator\NativeLabelTranslatorStrategy()));
    $o = ($this->services['sonata.admin.event.extension'] ?? $this->load('getSonata_Admin_Event_ExtensionService.php'));

    $a->setManagerType('orm');
    $a->setModelManager($b);
    $a->setFormContractor($c);
    $a->setShowBuilder($d);
    $a->setListBuilder($e);
    $a->setDatagridBuilder($f);
    $a->setTranslator($g, false);
    $a->setConfigurationPool($h);
    $a->setRouteGenerator($i);
    $a->setValidator($j);
    $a->setSecurityHandler($k);
    $a->setMenuFactory($l);
    $a->setRouteBuilder($m);
    $a->setLabelTranslatorStrategy($n);
    $a->setPagerType('default');
    $a->setLabel('Здание');
    $a->showMosaicButton(true);
    $a->setTemplateRegistry(($this->services['admin.building.template_registry'] ?? $this->load('getAdmin_Building_TemplateRegistryService.php')));
    $a->setSecurityInformation(array());
    $a->initialize();
    $a->addExtension($o);
    $a->setFormTheme(array(0 => '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'));
    $a->setFilterTheme(array(0 => '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig'));

    $instance->addChild($a);
    $instance->setManagerType('orm');
    $instance->setModelManager($b);
    $instance->setFormContractor($c);
    $instance->setShowBuilder($d);
    $instance->setListBuilder($e);
    $instance->setDatagridBuilder($f);
    $instance->setTranslator($g, false);
    $instance->setConfigurationPool($h);
    $instance->setRouteGenerator($i);
    $instance->setValidator($j);
    $instance->setSecurityHandler($k);
    $instance->setMenuFactory($l);
    $instance->setRouteBuilder($m);
    $instance->setLabelTranslatorStrategy($n);
    $instance->setPagerType('default');
    $instance->setLabel('Слайд');
    $instance->showMosaicButton(true);
    $instance->setTemplateRegistry(($this->services['admin.slide.template_registry'] ?? $this->load('getAdmin_Slide_TemplateRegistryService.php')));
    $instance->setSecurityInformation(array());
    $instance->initialize();
    $instance->addExtension($o);
    $instance->setFormTheme(array(0 => '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'));
    $instance->setFilterTheme(array(0 => '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig'));

    return $instance;
};

return $this->factories['admin.slide']();
